namespace mvvm44.ViewModels;

using System.Collections.Generic;

using System;

public class MainWindowViewModel : ViewModelBase
{
    public MainWindowViewModel()
    {
        string text1 = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras et augue a turpis aliquet consequat. Maecenas pretium, tortor eu euismod dapibus, orci lacus maximus felis, non facilisis tellus lectus vitae nunc. Nulla suscipit magna vitae porttitor accumsan. Nunc eleifend libero nec blandit ullamcorper. Donec posuere nunc id risus accumsan porttitor. Etiam vel sodales odio, ac commodo enim. Curabitur at augue orci. Maecenas interdum interdum consectetur. Suspendisse potenti. Aliquam sed commodo nisi. Nullam varius interdum elit vitae volutpat. Cras pulvinar id massa at tristique. Etiam euismod aliquet lacus ut egestas. Morbi felis mi, pharetra ac facilisis vel, laoreet at tortor. Praesent sollicitudin nulla nec consectetur hendrerit. Nam facilisis magna in ante scelerisque, ac tincidunt lacus hendrerit. Duis consectetur interdum pellentesque. Sed at venenatis eros. Donec metus dui, pellentesque vel dui at, commodo lobortis justo. Cras interdum dapibus tristique. Praesent eu dolor in risus feugiat consequat fermentum quis velit. Nunc id lectus vitae arcu sodales porta vehicula sit amet enim. Etiam erat est, aliquet ultricies blandit sit amet, accumsan nec lacus. Proin at dapibus sem, nec ultricies ligula. Aliquam vel nisi ac sem maximus rhoncus laoreet ac nunc. Pellentesque ante nulla, efficitur a feugiat eget, pellentesque sit amet ante. Sed scelerisque auctor ipsum in sodales. Proin lectus turpis, efficitur eget dolor non, suscipit varius mauris. Proin pretium tincidunt luctus. Sed dolor urna, faucibus sit amet sollicitudin ut, gravida hendrerit risus. Vestibulum congue erat quis leo commodo eleifend. Vestibulum ut ante a neque imperdiet tempus. Proin tincidunt magna ut ligula fermentum malesuada vel nec diam. Sed vel sem scelerisque, vehicula dolor non, pellentesque orci. Aliquam erat volutpat.";
        string text2 = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean sollicitudin pretium libero, nec pharetra mi dictum eu. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean rutrum purus ante, quis pretium sem suscipit in. Nullam consequat lobortis dolor eu tincidunt. In consequat, nibh vitae tincidunt ultricies, felis orci iaculis massa, id auctor nisi sapien in magna. Integer consequat sapien mi, eget dictum nisl ultricies vitae. Sed congue ex augue, ac facilisis justo ornare quis. Praesent et lorem eu elit sagittis euismod. Donec faucibus a mauris non congue. Sed faucibus malesuada erat rhoncus imperdiet. Suspendisse iaculis ante finibus tincidunt viverra. Suspendisse potenti. Nam quis fringilla libero. Fusce placerat elit arcu, eget porta dolor porttitor euismod. Nullam non lectus sit amet quam ultrices semper. Fusce vitae justo finibus, aliquam mi vitae, porta leo. Morbi non elementum urna, eget tempus lacus. Integer sollicitudin neque ligula, at pharetra justo mattis efficitur. Etiam dignissim sed nulla non congue. Nullam viverra convallis dolor at luctus.";
        string text3 = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin in magna dolor. Integer accumsan nec orci lacinia faucibus. Vestibulum consectetur feugiat dolor eu malesuada. Sed vel auctor enim. Morbi sodales dolor lorem, at congue elit tristique id. Fusce lobortis nisi nec velit sodales, sed viverra velit volutpat. Proin odio orci, gravida et odio at, suscipit venenatis nulla. Etiam rhoncus molestie lorem, sit amet porta arcu vehicula at. Cras odio mi, ornare ut laoreet vel, porttitor tincidunt nisl. Mauris ac aliquam dolor. Proin convallis laoreet elit quis blandit. Nunc dolor neque, finibus in metus vitae, volutpat ornare turpis. In non tempus tortor, sagittis venenatis lectus. Nulla sit amet velit non orci gravida convallis quis vel felis. Etiam faucibus aliquet quam, dignissim egestas ligula bibendum ac. Quisque tincidunt lacus felis. Phasellus quis nisi vel quam pellentesque ullamcorper. Vestibulum lobortis sapien vitae justo eleifend rutrum. Nam at urna a nisl varius pellentesque sed nec lectus. Maecenas consequat sit amet felis sit amet semper. Sed semper, mauris et viverra vulputate, erat erat malesuada nibh, id congue arcu quam ut dolor. Vestibulum vitae mollis mauris. Aliquam sit amet lectus quam. Phasellus eget purus id est dictum fermentum vitae eget turpis. Ut eu dolor condimentum, sagittis nulla ut, rhoncus arcu. Sed eget ex eget nisl varius accumsan eget at tellus. Nulla velit mauris, ullamcorper non aliquet id, lacinia vitae felis. Cras ultricies tristique aliquet.";
        string news1 = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed mollis pretium mi, at volutpat elit eleifend eu. Morbi sit amet metus gravida, malesuada nisi et, suscipit neque. Nam justo tortor, maximus ut purus vitae, pulvinar venenatis leo. Cras feugiat magna vitae cursus tempus. In odio urna, efficitur ut libero eu, laoreet molestie purus. Aliquam erat volutpat. Nam vulputate erat quis lorem gravida, quis aliquet neque dapibus. Sed ligula elit, consectetur tempor justo congue...";
        string news2 = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc quis est non odio aliquam iaculis. Phasellus varius dapibus nisi id semper. Suspendisse eu elit ultricies, accumsan neque et, sollicitudin tellus. Nulla et lectus tortor. Morbi pulvinar semper tellus mollis varius. Maecenas risus diam, molestie venenatis ultricies vel, dictum ut felis. Proin ut varius sapien. Curabitur nulla metus, tincidunt vitae enim in, maximus viverra justo. Morbi aliquet neque mollis quam facilisis...";
        string news3 = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin eu diam dui. Sed eleifend dapibus ante in congue. Curabitur dui sapien, posuere non commodo sed, venenatis sollicitudin neque. Ut aliquet dolor augue, ac aliquam lectus posuere in. Pellentesque at orci mattis, varius quam quis, consectetur massa. Aliquam a tortor pellentesque, varius enim sit amet, lacinia ligula. Donec sollicitudin, mi ac consectetur consequat, nulla est molestie ipsum...";
        BlogEntities =
        [
            new BlogEntity {Article = "Заголовок 1", Text = text1, TagsList = ["Tag1, Tag2"], ImagePath="car.png"},
            new BlogEntity {Article = "Заголовок 2", Text = text2, TagsList = ["Tag12, Tag22"], ImagePath="blue_waves.png"},
            new BlogEntity {Article = "Заголовок 3", Text = text3, TagsList = ["Tag13, Tag23"], ImagePath="stickman.png"}
        ];
        NewsEntities =
        [
            new NewsEntity { Text = news1, PublishDate = DateTime.Now.AddDays(-2)},
            new NewsEntity { Text = news2, PublishDate = DateTime.Now.AddDays(-7)},
            new NewsEntity { Text = news3, PublishDate = DateTime.Now}
        ];
    }
    public List<BlogEntity> BlogEntities { get; set; }

    public List<NewsEntity> NewsEntities { get; set; }
}
